vim.g.indent_blankline_use_treesitter = true
vim.g.indent_blankline_show_current_context = true
vim.g.indent_blankline_show_first_indent_level = false
vim.g.indent_blankline_filetype_exclude = {'startify', 'far', 'gitcommit', 'terminal', 'floaterm', 'NvimTree'}
vim.g.indent_blankline_enabled = true
vim.g.indent_blankline_show_trailing_blankline_indent = true
vim.g.indent_blankline_char_highlight = 'IndentBlankLineChar'
vim.g.indent_blankline_context_highlight = 'IndentBlankLineContext'
vim.g.indent_blankline_char = '┆'
vim.g.indent_blankline_space_char_highlight_list = {}
