vim.api.nvim_command('source ~/.config/nvim/lua/plugin-configurations/barbar.vim')
require('plugin-configurations.telescope')
require('plugin-configurations.dashboard-nvim')
require('plugin-configurations.vim-rooter')
require('plugin-configurations.floaterm')
require('plugin-configurations.lspkind-nvim')
require('plugin-configurations.lspsaga')
require('plugin-configurations.lsp-trouble')
require('plugin-configurations.lsp-colors')
require('plugin-configurations.nvim-compe')
require('plugin-configurations.nvim-lightbulb')
require('plugin-configurations.nvim-tree')
require('plugin-configurations.treesitter')
require('plugin-configurations.neoscroll')
