vim.api.nvim_command('source ~/.config/nvim/lua/plugin-configurations/barbar.vim')
require('plugin-configurations.telescope')
require('plugin-configurations.dashboard-nvim')
require('plugin-configurations.vim-rooter')
require('plugin-configurations.floaterm')
require('plugin-configurations.lspkind-nvim')
require('plugin-configurations.lspsaga')
require('plugin-configurations.lsp-trouble')
require('plugin-configurations.nvim-cmp')
require('plugin-configurations.nvim-lightbulb')
require('plugin-configurations.nvim-tree')
require('plugin-configurations.treesitter')
require('plugin-configurations.neoscroll')

--

require('plugin-configurations.anyfold')
require('plugin-configurations.asynctask')
vim.api.nvim_command('source ~/.config/nvim/lua/plugin-configurations/asynctask.vim')
require('plugin-configurations.better-whitespace')
require('plugin-configurations.coc')
require('plugin-configurations.colorizer')
require('plugin-configurations.diffview-nvim')
require('plugin-configurations.easy-align')
require('plugin-configurations.fugitive')
vim.api.nvim_command('source ~/.config/nvim/lua/plugin-configurations/fzf.vim')
require('plugin-configurations.galaxyline')
require('plugin-configurations.gitsigns')
require('plugin-configurations.highlightyank')
require('plugin-configurations.hop')
-- require('plugin-configurations.kommentary')
require('plugin-configurations.markdown-preview')
require('plugin-configurations.maximizer')
require('plugin-configurations.neoclip')
-- require('plugin-configurations.nerdcommenter')
require('plugin-configurations.nvim-autopairs')
require('plugin-configurations.nvim-comment')
require('plugin-configurations.octo')
require('plugin-configurations.package-info-nvim')
require('plugin-configurations.polyglot')
require('plugin-configurations.quickscope')
require('plugin-configurations.rnvimr')
require('plugin-configurations.symbols-outline-nvim')
require('plugin-configurations.spectre')
require('plugin-configurations.todo-comments')
require('plugin-configurations.ultisnips')
require('plugin-configurations.indent-blankline')
require('plugin-configurations.vim-bookmarks')
require('plugin-configurations.vim-illuminate')
require('plugin-configurations.vim-rooter')
require('plugin-configurations.vimspector')
require('plugin-configurations.windowswap')
